---
- name: Ensure apache is installed
  apt: name=apache2 state=present

- name: creates directory
  file: path=/var/www/html/ansible state=directory

- name: ensure apache is running
  service: name=apache2 enabled=yes state=started

- name: deploy config file
  template: src=templates/index.html dest=/etc/httpd/conf/httpd.conf
  notify:
    - Restart apache2

- name: copy site files
  template: src=templates/index.j2 dest={{doc_root}}/index.html mode=0644
